
server:
  port: 8222
spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: booking-service
          uri: lb:http://BOOKING-SERVICE
          predicates:
            - Path=/bookings/**
        - id: order-service
          uri: lb:http://MOVIE-SERVICE
          predicates:
            - Path=/movies/**
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: payment-service
          uri: lb:http://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
        - id: notification-service
          uri: lb:http://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**
        - id: roomseat-service
          uri: lb:http://ROOMSEAT-SERVICE
          predicates:
            - Path=/roomseats/**
      globalcors:
        cors-configurations:
          '[/**]': # Applies to all paths
            allowedOriginPatterns:
              - "http://localhost:*"
            allowedMethods: GET, POST, PUT, DELETE, OPTIONS
            allowedHeaders: "*"
            allowCredentials: true