spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://postgres-hdv:5432/booking_service_hdv
    username: postgres
    password: han1662003
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Options: create, create-drop, update, validate, none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: kafka:9092
      group-id: booking-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: payment:com.nguyenhan.hdv.model.Payment
  main:
    allow-bean-definition-overriding: true
  data:
    jpa:
      repositories:
        enabled: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    prefer-ip-address: true

