spring:
  application:
    name: roomseat-service
  datasource:
    url: jdbc:postgresql://localhost:5432/roomseat-service-hdv
    username: postgres
    password: han1662003
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Options: create, create-drop, update, validate, none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka Server URL
      register-with-eureka: true
      fetch-registry: true
