spring:
  application:
    name: user-service
  config:
    import: configserver:http://config-server:8888
  profiles:
    active: docker

---
spring:
  config:
    import: configserver:http://config-server:8888
  activate:
    on-profile: docker
