openapi: 3.0.0
info:
  title: Notification Service API
  version: 1.0.0
  description: API documentation for Notification Service

servers:
  - url: http://localhost:8085
    description: Local development server

paths:
  /notifications:
    post:
      summary: Send a notification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationRequest'
      responses:
        '200':
          description: Notification sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'

components:
  schemas:
    Notification:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        message:
          type: string
    
    NotificationRequest:
      type: object
      required:
        - userId
        - message
      properties:
        userId:
          type: string
        message:
          type: string 