spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: discovery-service

---
spring:
  config:
    import: configserver:http://config-server:8888
  activate:
    on-profile: docker