
#server:
#  port: 8222
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888

---
spring:
  config:
    import: configserver:http://config-server:8888
  activate:
    on-profile: docker